locale                   : "en-US"
remote_theme: pages-themes/architect
title                    : "Bill Hasling / Research Software Engineer"
title_separator          : "-"
name                     : &name "Bill Hasling"
description              : &description "personal description"
url                      : hhttps://github.com/bhasling/demo_page # the base hostname & protocol for your site e.g. "https://[your GitHub username].github.io"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "https://github.com/bhasling/demo_page"